Repository OpenDevicePartnership/patina, pull requests merged in 2025-10, with the labels that each got.

#841 chore: Release v11.2.0
  Cargo.toml
Labels: impact:non-functional

#845 patina_debugger: Remove initial breakpoint configurability.
  core/patina_debugger/src/debugger.rs
  core/patina_debugger/src/lib.rs
  docs/src/dev/debugging.md
Labels: type:design-change

#844 Docs: Update Debugger Recommendations
  docs/src/dev/debugging.md
  docs/src/integrate/dxe_core.md
Labels: impact:non-functional, type:documentation
